fragment MenuParts on Menu {
  __typename
  categories {
    __typename
    id
    name
    items {
      __typename
      id
      name
      description
      price
      image
      available
      calories
      protein
      isCombo
      maxSelections
      hasComplements
      maxComplements
      subItems {
        __typename
        id
        name
        description
      }
      complements {
        __typename
        id
        name
        price
      }
    }
  }
}
