//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  menu: Menu;
  menuConnection: MenuConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMenuArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMenuConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MenuFilter>;
};

export type DocumentFilter = {
  menu?: InputMaybe<MenuFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Menu | Folder;

export type MenuCategoriesItemsSubItems = {
  __typename?: 'MenuCategoriesItemsSubItems';
  id?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type MenuCategoriesItems = {
  __typename?: 'MenuCategoriesItems';
  id?: Maybe<Scalars['Float']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  available?: Maybe<Scalars['Boolean']['output']>;
  calories?: Maybe<Scalars['Float']['output']>;
  protein?: Maybe<Scalars['String']['output']>;
  isCombo?: Maybe<Scalars['Boolean']['output']>;
  maxSelections?: Maybe<Scalars['Float']['output']>;
  subItems?: Maybe<Array<Maybe<MenuCategoriesItemsSubItems>>>;
};

export type MenuCategories = {
  __typename?: 'MenuCategories';
  id?: Maybe<Scalars['Float']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<MenuCategoriesItems>>>;
};

export type Menu = Node & Document & {
  __typename?: 'Menu';
  categories?: Maybe<Array<Maybe<MenuCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type MenuCategoriesItemsSubItemsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type MenuCategoriesItemsFilter = {
  id?: InputMaybe<NumberFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  available?: InputMaybe<BooleanFilter>;
  calories?: InputMaybe<NumberFilter>;
  protein?: InputMaybe<StringFilter>;
  isCombo?: InputMaybe<BooleanFilter>;
  maxSelections?: InputMaybe<NumberFilter>;
  subItems?: InputMaybe<MenuCategoriesItemsSubItemsFilter>;
};

export type MenuCategoriesFilter = {
  id?: InputMaybe<NumberFilter>;
  name?: InputMaybe<StringFilter>;
  items?: InputMaybe<MenuCategoriesItemsFilter>;
};

export type MenuFilter = {
  categories?: InputMaybe<MenuCategoriesFilter>;
};

export type MenuConnectionEdges = {
  __typename?: 'MenuConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Menu>;
};

export type MenuConnection = Connection & {
  __typename?: 'MenuConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MenuConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateMenu: Menu;
  createMenu: Menu;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateMenuArgs = {
  relativePath: Scalars['String']['input'];
  params: MenuMutation;
};


export type MutationCreateMenuArgs = {
  relativePath: Scalars['String']['input'];
  params: MenuMutation;
};

export type DocumentUpdateMutation = {
  menu?: InputMaybe<MenuMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  menu?: InputMaybe<MenuMutation>;
};

export type MenuCategoriesItemsSubItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type MenuCategoriesItemsMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  available?: InputMaybe<Scalars['Boolean']['input']>;
  calories?: InputMaybe<Scalars['Float']['input']>;
  protein?: InputMaybe<Scalars['String']['input']>;
  isCombo?: InputMaybe<Scalars['Boolean']['input']>;
  maxSelections?: InputMaybe<Scalars['Float']['input']>;
  subItems?: InputMaybe<Array<InputMaybe<MenuCategoriesItemsSubItemsMutation>>>;
};

export type MenuCategoriesMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<MenuCategoriesItemsMutation>>>;
};

export type MenuMutation = {
  categories?: InputMaybe<Array<InputMaybe<MenuCategoriesMutation>>>;
};

export type MenuPartsFragment = { __typename: 'Menu', categories?: Array<{ __typename: 'MenuCategories', id?: number | null, name?: string | null, items?: Array<{ __typename: 'MenuCategoriesItems', id?: number | null, name?: string | null, description?: string | null, price?: number | null, image?: string | null, available?: boolean | null, calories?: number | null, protein?: string | null, isCombo?: boolean | null, maxSelections?: number | null, subItems?: Array<{ __typename: 'MenuCategoriesItemsSubItems', id?: string | null, name?: string | null, description?: string | null } | null> | null } | null> | null } | null> | null };

export type MenuQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MenuQuery = { __typename?: 'Query', menu: { __typename: 'Menu', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'MenuCategories', id?: number | null, name?: string | null, items?: Array<{ __typename: 'MenuCategoriesItems', id?: number | null, name?: string | null, description?: string | null, price?: number | null, image?: string | null, available?: boolean | null, calories?: number | null, protein?: string | null, isCombo?: boolean | null, maxSelections?: number | null, subItems?: Array<{ __typename: 'MenuCategoriesItemsSubItems', id?: string | null, name?: string | null, description?: string | null } | null> | null } | null> | null } | null> | null } };

export type MenuConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MenuFilter>;
}>;


export type MenuConnectionQuery = { __typename?: 'Query', menuConnection: { __typename?: 'MenuConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MenuConnectionEdges', cursor: string, node?: { __typename: 'Menu', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'MenuCategories', id?: number | null, name?: string | null, items?: Array<{ __typename: 'MenuCategoriesItems', id?: number | null, name?: string | null, description?: string | null, price?: number | null, image?: string | null, available?: boolean | null, calories?: number | null, protein?: string | null, isCombo?: boolean | null, maxSelections?: number | null, subItems?: Array<{ __typename: 'MenuCategoriesItemsSubItems', id?: string | null, name?: string | null, description?: string | null } | null> | null } | null> | null } | null> | null } | null } | null> | null } };

export const MenuPartsFragmentDoc = gql`
    fragment MenuParts on Menu {
  __typename
  categories {
    __typename
    id
    name
    items {
      __typename
      id
      name
      description
      price
      image
      available
      calories
      protein
      isCombo
      maxSelections
      subItems {
        __typename
        id
        name
        description
      }
    }
  }
}
    `;
export const MenuDocument = gql`
    query menu($relativePath: String!) {
  menu(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MenuParts
  }
}
    ${MenuPartsFragmentDoc}`;
export const MenuConnectionDocument = gql`
    query menuConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MenuFilter) {
  menuConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MenuParts
      }
    }
  }
}
    ${MenuPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      menu(variables: MenuQueryVariables, options?: C): Promise<{data: MenuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuQueryVariables, query: string}> {
        return requester<{data: MenuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuQueryVariables, query: string}, MenuQueryVariables>(MenuDocument, variables, options);
      },
    menuConnection(variables?: MenuConnectionQueryVariables, options?: C): Promise<{data: MenuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuConnectionQueryVariables, query: string}> {
        return requester<{data: MenuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuConnectionQueryVariables, query: string}, MenuConnectionQueryVariables>(MenuConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.6/content/d7845957-b978-4c25-8002-4c1f394523c8/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  