backend:
  name: github
  repo: NicolasYMonteiro/site-zen-marmitas
  branch: main
  # Para autenticação, configure o GitHub OAuth App ou use o Netlify Identity/Git Gateway

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - file: "public/data/menu.json"
        label: "Menu JSON"
        name: "menujson"
        format: "json"
        fields:
          - { label: "Itens do Menu", name: "items", widget: "list", fields: [ {label: "Nome", name: "name", widget: "string"}, {label: "Preço", name: "price", widget: "number"}, {label: "Descrição", name: "description", widget: "string", required: false} ] }
