backend:
  name: github
  repo: NicolasYMonteiro/site-zen-marmitas
  branch: main
  # Para autenticação, configure o GitHub OAuth App ou use o Netlify Identity/Git Gateway

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Cardápio Completo"
    files:
      - file: "public/data/menu.json"
        label: "Menu JSON"
        name: "menujson"
        format: "json"
        fields:
          - label: "Categorias"
            name: "categories"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number", value_type: "int" }
              - { label: "Nome", name: "name", widget: "string" }
              - label: "Itens"
                name: "items"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "number", value_type: "int" }
                  - { label: "Nome", name: "name", widget: "string" }
                  - { label: "Descrição", name: "description", widget: "text" }
                  - { label: "Preço", name: "price", widget: "number", value_type: "float", step: 0.01 }
                  - { label: "Imagem", name: "image", widget: "image", required: false }
                  - label: "Disponível"
                    name: "available"
                    widget: "boolean"
                    required: false
                    hint: "Deixe vazio para manter o valor atual"
                  - { label: "Calorias", name: "calories", widget: "number", value_type: "int", required: false }
                  - { label: "Proteína", name: "protein", widget: "string", required: false }
                  - label: "É Combo"
                    name: "isCombo"
                    widget: "boolean"
                    required: false
                    hint: "Deixe vazio para manter o valor atual"
                  - { label: "Máximo de Seleções", name: "maxSelections", widget: "number", value_type: "int", required: false }
                  - label: "Sub-itens (para combos)"
                    name: "subItems"
                    widget: "list"
                    required: false
                    fields:
                      - { label: "ID", name: "id", widget: "string" }
                      - { label: "Nome", name: "name", widget: "string" }
                      - { label: "Descrição", name: "description", widget: "text" }