backend:
  name: github
  repo: nicol/site-zen-marmitas # Substitua pelo seu repositório
  branch: main

# Configuração de autenticação
publish_mode: editorial_workflow

# Configuração de mídia
media_folder: "public/images/menu"
public_folder: "/images/menu"

# Configurações do site
site_url: https://mamitashvc.vercel.app # Substitua pelo seu domínio
display_url: https://mamitashvc.vercel.app # Substitua pelo seu domínio

# Configuração de coleções
collections:
  # Coleção para o cardápio completo
  - name: "menu"
    label: "Cardápio Completo"
    files:
      - label: "Cardápio"
        name: "menu"
        file: "public/data/menu.json"
        fields:
          - label: "Categorias"
            name: "categories"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Nome", name: "name", widget: "string"}
              - label: "Itens"
                name: "items"
                widget: "list"
                fields:
                  - {label: "ID", name: "id", widget: "number", value_type: "int"}
                  - {label: "Nome", name: "name", widget: "string"}
                  - {label: "Descrição", name: "description", widget: "text"}
                  - {label: "Preço", name: "price", widget: "number", value_type: "float", step: 0.01}
                  - {label: "Imagem", name: "image", widget: "image", required: false}
                  - {label: "Disponível", name: "available", widget: "boolean", default: true}
                  - {label: "Calorias", name: "calories", widget: "number", value_type: "int", required: false}
                  - {label: "Proteína", name: "protein", widget: "string", required: false}
                  - {label: "É Combo", name: "isCombo", widget: "boolean", default: false}
                  - {label: "Máximo de Seleções", name: "maxSelections", widget: "number", value_type: "int", required: false}
                  - label: "Sub-itens (para combos)"
                    name: "subItems"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "ID", name: "id", widget: "string"}
                      - {label: "Nome", name: "name", widget: "string"}
                      - {label: "Descrição", name: "description", widget: "text"}
